#!/bin/sh

config=/bin/config

/usr/sbin/rmmod nf_nat_dnisip.ko > /dev/null
/usr/sbin/rmmod nf_conntrack_dnisip.ko > /dev/null

if [ "$($config get wan_endis_sipalg)" != "1" ]; then
	/usr/sbin/insmod nf_conntrack_dnisip.ko
	/usr/sbin/insmod nf_nat_dnisip.ko
fi
