#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

do_dni_mount_root() {

	# ramoverlay
	mkdir -p /tmp/mnt
	mkdir -p /tmp/root

	/bin/mount -t tmpfs -o noatime,mode=0755 root /tmp/root
	mkdir -p /tmp/root/root /tmp/root/work
	fopivot /tmp/root/root /tmp/root/work /rom 1

	if [ -z "$(grep vol_traffic /proc/mtd)" -a -n "$(grep ntgrdata /proc/mtd)" ]; then
		echo "Info: init ubi volumes on ntgrdata raw partition"

		mtdn=$(sed -nr 's/mtd([0-9]*):.*"ntgrdata"/\1/p' /proc/mtd)
		if [ -z "$mtdn" ]; then
			echo "Error: can't find ntgrdata partition in mtd device!"
		else
			ubiattach /dev/ubi_ctrl -m $mtdn
			if [ -n "$(grep vol_traffic /proc/mtd)" ]; then
				echo "Info: attach ubi device on ntgrdata success!"
			else
				ubinize -m 2048 -p 128KiB -o /tmp/ntgrdata.ubi /etc/ntgrdata.cfg
				ubidetach /dev/ubi_ctrl -m $mtdn
				flash_erase /dev/mtd$mtdn 0 0
				nandwrite -p /dev/mtd$mtdn /tmp/ntgrdata.ubi
				ubiattach /dev/ubi_ctrl -m $mtdn
			fi
		fi

		if [ -z "$(grep vol_traffic /proc/mtd)" ]; then
			echo "Error: create ubi volumes on ntgrdata raw partition fail!"
		fi
	fi

	if [ -z "$(grep vol_pot /proc/mtd)" -a -n "$(grep dnidata /proc/mtd)" ]; then
		echo "Info: init ubi volumes on dnidata raw partition"

		mtdn=$(sed -nr 's/mtd([0-9]*):.*"dnidata"/\1/p' /proc/mtd)
		if [ -z "$mtdn" ]; then
			echo "Error: can't find dnidata partition in mtd device!"
		else
			ubiattach /dev/ubi_ctrl -m $mtdn
			if [ -n "$(grep vol_pot /proc/mtd)" ]; then
				echo "Info: attach ubi device on dnidata success!"
			else
				ubinize -m 2048 -p 128KiB -o /tmp/dnidata.ubi /etc/dnidata.cfg
				ubidetach /dev/ubi_ctrl -m $mtdn
				flash_erase /dev/mtd$mtdn 0 0
				nandwrite -p /dev/mtd$mtdn /tmp/dnidata.ubi
				ubiattach /dev/ubi_ctrl -m $mtdn
			fi
		fi
		
		if [ -z "$(grep vol_pot /proc/mtd)" ]; then
			echo "Error: create ubi volumes on dnidata raw partition fail!"
		fi
	fi
	if ! ubinfo /dev/ubi0 -N vol_ntgrcryptD; then
		ubimkvol /dev/ubi0 -s 3MiB -N vol_ntgrcryptD
	fi
	if ! ubinfo /dev/ubi0 -N vol_ntgrcryptK; then
		ubimkvol /dev/ubi0 -s 512KiB -N vol_ntgrcryptK
	fi
}

do_mount_root() {
	echo "Before mount_root"

	# mount_root
	# boot_run_hook preinit_mount_root
	do_dni_mount_root

	[ -f /sysupgrade.tgz ] && {
		echo "- config restore -"
		cd /
		tar xzf /sysupgrade.tgz
	}
	echo "After mount_root"
}

[ "$INITRAMFS" = "1" ] || boot_hook_add preinit_main do_mount_root
